x-base-env: &base-env
  DB_SOCKET_PATH: /sockets/database.sock

services:
  payments-service: &payments-service
    build:
      context: .
      target: dev
      dockerfile: payments-service/Dockerfile
    environment:
      <<: *base-env
      SERVICE_NUMBER: 1
      SOCKET_PATH: /sockets/payments-service-1.sock
    volumes:
      - ./:/pps/
      - sockets-volume:/sockets
    working_dir: /pps
    depends_on:
      - database
    networks:
      - backend
      - payment-processor

  payments-service-2:
    <<: *payments-service
    build:
      context: .
      target: dev
      dockerfile: payments-service/Dockerfile.service2
    environment:
      <<: *base-env
      SERVICE_NUMBER: 2
      SOCKET_PATH: /sockets/payments-service-2.sock
    volumes:
      - ./:/pps2/
      - sockets-volume:/sockets
    working_dir: /pps2/
    depends_on:
      - database
    networks:
      - backend
      - payment-processor

  load-balancer-backend:
    build:
      context: .
      target: dev
      dockerfile: load-balancer-backend/Dockerfile
    ports:
      - "9999:9999"
    environment:
      - PORT=9999
      - SOCKET1_PATH=/sockets/payments-service-1.sock
      - SOCKET2_PATH=/sockets/payments-service-2.sock
    volumes:
      - ./:/lbb/
      - sockets-volume:/sockets
    depends_on:
      - payments-service
      - payments-service-2
    networks:
      - backend
      - payment-processor

  database:
    build:
      context: .
      target: dev
      dockerfile: database/Dockerfile
    environment:
      - SOCKET_PATH=/sockets/database.sock
    volumes:
      - ./:/db/
      - sockets-volume:/sockets
    networks:
      - backend


networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
  sockets-volume: